name: Build Mod

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack (zip prêt à mettre dans Mods)
      shell: pwsh
      run: |
        $out = "package"
        New-Item -ItemType Directory -Force -Path $out | Out-Null
        Copy-Item manifest.json $out/
        # récupère automatiquement la DLL compilée dans net5.0
        $dll = Get-ChildItem -Recurse -Filter *.dll | Where-Object { $_.FullName -match "bin\\Release\\net5.0" }
        Copy-Item $dll.FullName $out/
        Compress-Archive -Path "$out/*" -DestinationPath "LongerHugsAndKisses.zip" -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LongerHugsAndKisses
        path: LongerHugsAndKisses.zip
        
